### ISSUE TITLE
Generate frontend project architecture schematic.

### ISSUE THREAD

**Issue by JesielPalacios** [JesielPalacios/capellania-fi-reactjs#6]
Generar esquema de la arquitectura del proyecto frontend.

**Comment by antho1810** [comment]
Documentación:
https://drive.google.com/drive/folders/1BDQipxcQmi-S6WkpcHDaGz42C-JitpH7?usp=sharing

Diseño:
https://drive.google.com/drive/folders/1ukpFSjVGsKaxf-zoGOWxKlNPxqJZCuto?usp=sharing
